FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3-pip ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY back/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY back /app
CMD ["uvicorn", "back.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
