services:
  api:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports: ["8000:8000"]
    env_file:
      - back/.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
